CREATE SEQUENCE supplier_seq
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE customer_seq
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE supplier_wf_seq
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE customer_wf_seq
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE product_wf_seq
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE product_seq
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE po_wf_seq
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE po_seq
START WITH 1
INCREMENT BY 1;

