create table USER
(USER_ID VARBINARY primary key,
CONTACT_NO VARCHAR(255),CREATED_BY VARCHAR(255),CREATION_TIMESTAMP TIMESTAMP,
EMAIL_ID VARCHAR(255),FIRST_NAME VARCHAR(255),LAST_LOGIN_TIME TIMESTAMP ,
LAST_NAME VARCHAR(255),MIDDLE_NAME VARCHAR(255) ,MODIFIED_BY VARCHAR(255),MODIFIED_TIMESTAMP TIMESTAMP,
PASSWORD VARCHAR(255) ,SUPERVISOR_ID VARCHAR(255), ROLE_ID INTEGER(2),
FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID)
);

create table ROLE
(ROLE_ID INTEGER(2) primary key ,ROLENAME VARCHAR(255) );

